### ISSUE TITLE
Name Changer/Kerb editor

### ISSUE THREAD

**Issue by Fluburtur** [KAmaia/KerbalGenerator#1]
What it says, edit a Kerbal's name, gender, role and most importantly: BADASS

**Comment by KAmaia** [comment]
Closing:
This functionality is currently available through the central pane.  Type the name of the Kerbal you want to rename in Basic Info: Name, Change their gender, badassery, tourismery, profession, bravery or stupidity, Click generate and it will preview/ask if you want to over-write the kerbal.  WARNING: This will Ressurect dead kerbals reset the kerbals flights to 0, and potentially other buggy behavior.  I am working on that though.
