### ISSUE TITLE
Looking in the wrong path for persistent.sfs

### ISSUE THREAD

**Issue by umaxtu** [KAmaia/KerbalGenerator#5]
Note: I built the code on Linux and am running on Linux. If that is the cause of the issue and you don't want to support Linux, feel free to ignore.
### Here is the error that I get when I try to run it again after I create the config and it crashes:

`System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/umaxtu/code/c#/KerbalGenerator/KerbalGenerator/KSP_linux/saves/KSP_linux/saves/default/persistent.sfs".`
Notice the path? Specifically the part where KSP_linux/saves is doubled up?
### Here is the contents of .config/BadWater/KerbalGen/config.xml:

`<?xml version="1.0"?>
<configuration>
  <ksp name="test">
    <save name="KSP_linux/saves/default" path="KSP_linux/saves/default/persistent.sfs" />
  </ksp>
</configuration>`
### Here is the contents of .config/BadWater/KerbalGen/Config/config.xml:

`<?xml version="1.0"?>
<configuration>
  <ksp name="test">
    <save name="KSP_linux/saves/default" path="KSP_linux/saves/KSP_linux/saves/default/persistent.sfs" />
    <save name="KSP_linux/saves/scenarios" path="KSP_linux/saves/KSP_linux/saves/scenarios/persistent.sfs" />
    <save name="KSP_linux/saves/training" path="KSP_linux/saves/KSP_linux/saves/training/persistent.sfs" />
  </ksp>`
I wasn't sure what the difference was between the two config.xmls so I included both of them.

**Comment by KAmaia** [comment]
Thanks!  Wow, Logs come in handy!  
I'll get right on it!

**Comment by KAmaia** [comment]
Umaxtu, I'm not sure what's happening on your end, I'm unable to replicate this bug.  Also I don't know why it is creating two seperate config paths, unless you were using an inbetween version.  Try clearing .config/Badwater/KerbalGen/ and relaunching.

**Comment by umaxtu** [comment]
Seems to work now. But I did notice that in Windows, it would throw an error if I tell it that my savepath is KSP_ROOT/saves. I would assume that this could be fixed by checking if the provided path already includes a directory called "saves" at the end before adding it to the provided path.

**Comment by KAmaia** [comment]
Thanks for the feedback Umaxtu.  Would you say I can close this?

**Comment by umaxtu** [comment]
Yeah you can close it
